FROM mysql

ENV MYSQL_ROOT_PASSWORD 1234

# docker build -t mysql-image -f api/db/Dockerfile .

# docker image ls

# docker run -d -v /absolute/path/to/api/db/data:/var/lib/mysql --rm --name mysql-container mysql-image

# docker ps